name = "anti-spam-bot"
type = "javascript"
account_id = "864cdf76f8254fb5539425299984d766"
workers_dev = false
routes = ["https://verify.workers.community", "https://verify.workers.community/*"]
zone_id = "c5de466b2a57eb411ca73273c83e0421"

kv_namespaces = [ { binding = "database", id = "cded7f3e83a64c0db24c3cca2f7a14c1", preview_id = "cded7f3e83a64c0db24c3cca2f7a14c1" }]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"